// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyBase.Support.Infrastructure.Persistence;

#nullable disable

namespace MoneyBase.Support.Infrastructure.Migrations
{
    [DbContext(typeof(MoneyBaseContext))]
    [Migration("20251025220256__create-db")]
    partial class _createdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoneyBase.Support.Domain.Entities.Agent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AssignedChatIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOverflow")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Seniority")
                        .HasColumnType("int");

                    b.Property<int>("ShiftEndHour")
                        .HasColumnType("int");

                    b.Property<int>("ShiftStartHour")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("MoneyBase.Support.Domain.Entities.ChatSession", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AgentId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChatStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastPollAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("MoneyBase.Support.Domain.Entities.ChatSession", b =>
                {
                    b.HasOne("MoneyBase.Support.Domain.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId");

                    b.Navigation("Agent");
                });
#pragma warning restore 612, 618
        }
    }
}
